# Generated by Django 3.1.5 on 2021-01-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210114_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroku',
            name='text',
        ),
    ]
