# Generated by Django 3.1.5 on 2021-01-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_touroku_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroku',
            name='text',
            field=models.CharField(default='louis', max_length=30),
            preserve_default=False,
        ),
    ]
