# Generated by Django 3.1.5 on 2021-01-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_touroku_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroku',
            name='gender',
        ),
    ]
