# Generated by Django 3.1.5 on 2021-01-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_touroku_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroku',
            name='age',
        ),
    ]
